skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_program = "6j1BgEjsaqEwPuJ7GMKkRywt1rhPh4z38CWXFv5ytHjz"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
